---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.5:8001/eureka/

# Instructs the Spring-Config App where to locate
# the configurations for the client-services.
---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.org/sean-huni/config/
          searchPaths: secrets

        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repo/
server:
  port: 8002